### ISSUE TITLE
Allow to run script to discover only users but do not perform action

### ISSUE THREAD

**Issue by zampat** [caragian/Dashboard#3]
1) I would like to run the script with a parameter -d/--discover to just discover the users from AD group and show the usernames (samaccountnames)  in console.
But do not perform the action to distribute the dashboard.
2) Add also option -a/--action to activate the distribution of dasboards to discovered users.
3) Add also -h/--help option to show available options.
4) Make the use of parameters mandatory and show "usage" if no parameter is passed on script.

**Comment by caragian** [comment]
1. Done | No deploy
ex. python3 insert_dashboard.py -l authentication.json -d admin_group

2. I decided that to do this is require only to type -t Template in addition to first point.
ex. python3 insert_dashboard.py -l authentication.json -d admin_group -t template_windows

3. Done
4. Done
